name: "batterie_storcube"
description: "Lien entre Storcube et MQTT"
version: "1.0.0"
slug: "batterie_storcube"
arch:
  - aarch64
  - amd64
  - armv7
init: false
options:
  MQTT_BROKER: "192.168.1.18"
  MQTT_PORT: 1883
  LOGIN_NAME: "votre@email.com"
  PASSWORD: "votre_password"
  DEVICE_ID: "votre_id"
schema:
  MQTT_BROKER: str
  MQTT_PORT: int
  MQTT_USERNAME: str?
  MQTT_PASSWORD: password?
  LOGIN_NAME: str
  PASSWORD: password
  DEVICE_ID: str
